Project sms_db {
  database_type: 'PostgreSQL'
  Note: '''# Small Molecule Suite

  **Based on ChEMBL v27**

  The [Small Molecule Suite (SMS)](https://labsyspharm.shinyapps.io/smallmoleculesuite/)
  is a free, open-acces tool developed
  by the [Harvard Program in Therapeutic Sciences (HiTS)](https://hits.harvard.edu/).

  The database contains all data underlying SMS.

  The goal of the SMS is to help scientists understand and work with the targets
  of molecular probes, approved drugs and other drug-like molecules, while
  acknowledging the complexity of polypharmacology — the phenomenon that
  virtually all drug-like molecules bind multiple target proteins.

  SMS combines data from the ChEMBL database with prepublished data from the
  Laboratory of Systems pharmacology. The methodology of calculating
  selectivities and similarities are explained in Moret et al. Cell Chem Biol
  2019 (which can also be used to cite the Small Molecule Suite).
  '''
}

Enum approval_tiers {
  0 [note:"Not tested in any clinical trial."]
  1 [note:"Has been tested at most in phase I trials."]
  2 [note:"Has been tested at most in phase II trials."]
  3 [note:"Has been tested at most in phase III trials."]
  4 [note:"Is approved drug."]
}

Table lsp_compound_dictionary {
  lspci_id int [pk, note:"Internal compound ID"]
  hmsl_id varchar [note:"Primary HMS LINCS compound ID, if available"]
  chembl_id varchar [note:"Primary ChEMBL compound ID, if available"]
  emolecules_id int [note:"Primary EMolecules compound ID, if available"]
  pref_name varchar [note:"Preferred name of the compound"]
  inchi varchar [
    note:'''InChI chemical indentifier for the compound, standardized \
    using https://github.com/chembl/ChEMBL_Structure_Pipeline'''
  ]
  commercially_available boolean [
    note:"Indicates that compound is commercially available at a vendor in the eMolecules database"
  ]
  max_phase approval_tiers [note:"Approval and clinical trial status of the compound."]

  Note: '''
    Primary table listing all compounds in the database. \
    During compound processing distinct salts of the same compound \
    are aggregated into a single compound entry in this table. \
    The constituent compound IDs for each compound in this table \
    are available in the lsp_compound_mapping table.
  '''

  Indexes {
    hmsl_id
    chembl_id
    emolecules_id
    commercially_available
  }
}

Table lsp_structures {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  source compound_sources [note:"Source for the compound name"]
  rank int [note:"Rank of InCHI according to source reliability and annotation quality"]
  inchi varchar [
    note:'''InChI chemical indentifier for the compound, standardized \
    using https://github.com/chembl/ChEMBL_Structure_Pipeline'''
  ]

  Note: "Additional secondary InChIs for compounds."

  Indexes {
    lspci_id
  }
}

Enum name_priorities {
  primary [note:"Name annotated as primary name at source"]
  secondary [note:"Name annotated as secondary name at source"]
}

Enum compound_sources {
  chembl [note:"Derived from ChEMBL annotation"]
  hmsl [note:"Derived from HMS LINCS annotation"]
  emolecules [note:"Derived from vendor annotation at eMolecules"]
  old_sms [note:"Derived from an old version of the Small Molecules Suite. Might not be annotated anymore in ChEMBL"]
}

Table lsp_compound_names {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  source compound_sources [note:"Source for the compound name"]
  priority name_priorities [
    note:"Annotated as primary or secondary name at source"
  ]
  name varchar [note:"Compound name"]

  Note: '''
    Table of all annotated names for compounds. The sources \
    for compound names generally distinguish between primary and \
    alternative (secondary) names.
  '''

  Indexes {
    lspci_id
  }
}

Table lsp_compound_mapping {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  source compound_sources [note:"Source for the compound ID."]
  external_id varchar [note:"ID of the compound at the external source."]

  Note:'''
    Table of mappings between compound IDs from different sources to \
    the internal lspci_ids.
  '''

  Indexes {
    lspci_id
    external_id
  }
}

Table lsp_target_dictionary {
  lspci_target_id int [pk, note:"Internal target ID"]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  pref_name varchar [note:"Gene name"]
  tax_id int [note:"Entrez taxonomy ID"]
  organism varchar [note:"Organism for which gene is annotated"]

  Note:'''
    Table of drug targets. The original drug targets are mostly \
    annotated as ChEMBL or UniProt IDs. For convenience we converted \
    these IDs to Entrez gene IDs. The original mapping between \
    ChEMBL and UniProt target IDs are in the table `lsp_target_mapping`
  '''

  Indexes {
    symbol
    tax_id
    organism
  }
}

Enum target_types {
  "SINGLE PROTEIN"
  "CHIMERIC PROTEIN"
  "PROTEIN FAMILY"
  "SELECTIVITY GROUP"
  "PROTEIN COMPLEX GROUP"
  "PROTEIN COMPLEX"
  "PROTEIN NUCLEIC-ACID COMPLEX"
  "PROTEIN-PROTEIN INTERACTION"
}

Table lsp_target_mapping {
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key to lsp_target_dictionary table"
  ]
  chembl_id varchar [note:"ChEMBL target ID"]
  uniprot_id varchar [note:"UniProt ID"]
  target_type target_types [note:"The type of the original target before translation to Entrez IDs"]

  Note:'''
    Mapping between the original ChEMBL target IDs, \
    their corresponding UniProt IDs and Entrez gene IDs. \
    A single UniProt or ChEMBL ID can refer to protein complexes, \
    therefore multiple gene IDs often map to the same UniProt or \
    ChEMBL ID.
  '''

  Indexes {
    lspci_target_id
  }
}


Enum biochem_value_types {
  IC50
  Ki
  Kd
  MIC
  EC50
  Inhibition
  AC50
  ED50
  IC90
  Activity
  Potency
  ID50
  CC50
}

Enum biochem_value_relations {
  "="
  ">"
  "<"
  ">>"
  "<<"
  "~"
  "<="
  ">="
}

Enum biochem_value_units {
  nM
}

Enum reference_types {
  pubmed_id
  doi
  chembl_id
  patent_id
  synapse_id
  hmsl_id
}

Table lsp_references {
  reference_id int [pk, note:"Primary key"]
  reference_type reference_types [note:"The source of the measurement."]
  reference_value varchar [note:"The reference accesion number at the source."]
  url varchar [note:"URL to access the reference."]

  Note:"External references for the data in the database."

  Indexes {
    reference_value
  }
}

Table lsp_biochem {
  biochem_id int [pk, note:"Primary key"]
  biochem_agg_id int [
      ref: > lsp_biochem_agg.biochem_agg_id,
      note:"Foreign key to lsp_biochem_agg table. All measurments with the same ID are aggregated."
    ]
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  source compound_sources [note:"Source of the measurement"]
  description_assay varchar [note:"Description of the assay that the measurement is derived from"]
  value float [note:"Measurement value"]
  value_type biochem_value_types [note:"The type of measurement performed."]
  value_unit biochem_value_units [note:"The unit of the measurement."]
  value_relation biochem_value_relations [
    note:"Some assays can''t determine the measured value precisely. This column gives relationship between the actual and the measured value."
  ]
  reference_id int [
    ref: > lsp_references.reference_id,
    note:"Foreing key to the ls_reference table for this measurement."
  ]

  Note:'''
    Table of biochemical affinity measurements.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    (lspci_id, lspci_target_id)
    biochem_agg_id
    reference_id
  }
}

Table lsp_biochem_agg {
  biochem_agg_id int [
    pk,
    note:"All measurements with this ID in lsp_biochem were aggregated."
  ]
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  value float [note:"Aggregated measurement value"]
  value_unit biochem_value_units [note:"The unit of the measurement."]
  tas_id int [
    ref: > lsp_tas.tas_id,
    note:"Foreign key to lsp_tas table. Indicates that this value was used to calculate the referenced TAS."
  ]

  Note:'''
    Table of aggregated biochemical affinity measurements. All
    available data for a single compound target pair were aggregated
    by taking the first quartile.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    (lspci_id, lspci_target_id)
    biochem_agg_id
    tas_id
  }
}

Table lsp_phenotypic {
  phenotypic_id int [pk, note:"Primary key for phenotypic data."]
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  assay_id int [note:"Unique ID of the assays in the database. Correspond to ChEMBL assay IDs."]
  value float [note:"Measurement value"]
  value_type varchar [note:"The type of measurement performed."]
  value_unit biochem_value_units [note:"The unit of the measurement."]
  description_assay varchar [note:"Description of the assay."]
  reference_id int [
    ref: > lsp_references.reference_id,
    note:"Foreing key to the ls_reference table for this measurement."
  ]
  phenotypic_agg_id int [
    ref: > lsp_phenotypic_agg.phenotypic_agg_id,
     note:"Foreign key to lsp_phenotypic_agg table. All measurements with the same ID are aggregated."
  ]

  Note:'''
    Table of phenotypic assays performed on the compounds.
  '''

  Indexes {
    lspci_id
    assay_id
    (lspci_id, assay_id)
    phenotypic_agg_id
  }
}

Table lsp_phenotypic_agg {
  phenotypic_agg_id int [
    pk,
    note:"All measurements with this ID in lsp_phenotypic were aggregated."
  ]
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  assay_id int [note:"Unique ID of the assays in the database. Correspond to ChEMBL assay IDs."]
  value float [note:"Aggregated measurement value"]
  value_unit biochem_value_units [note:"The unit of the measurement."]
  rscore float [note:"Standardized measurement value."]
  rscore_tr float [note: "Rscore normalized using a double logistic function."]

  Note:'''
    Table of aggregated phenotypic assays performed on the compounds.
    All available data for a single assay and compound target pair were
    aggregated by taking the first quartile.
  '''

  Indexes {
    lspci_id
    assay_id
    (lspci_id, assay_id)
  }
}

Enum binding_data_types {
  dose_response [note:"Binding date derived from full dose-response measurement."]
  single_dose [note:"Binding data derived from the extent of inhibition at a single dose."]
  literature_annotation [note:"Binding data derived from manually curated annotations in the literature."]
}

Table lsp_tas {
  tas_id int [
    pk,
    note:"ID of this TAS value. The lsp_biochem_agg, lsp_one_dose_scan_agg, and lsp_manual_curation tables reference this ID in order to designate which value was used to calculate the TAS."
  ]
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  tas int [
    note:"Target Affinity Spectrum (TAS). A number between 1 and 10 for the affinity between compound and target. 1 being most strongly binding."
  ]
  derived_from binding_data_types [note:"Data type that the TAS value was derived from."]

  Note:'''
    Table of Target Affinity Spectrum (TAS) values for the affinity between \
    compound and target. TAS enables aggregation of affinity measurements from \
    heterogeneous sources and assays into a single value. See \
    10.1016/j.chembiol.2019.02.018 for details.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    (lspci_id, lspci_target_id)
    tas
  }
}

Table lsp_tas_references {
  tas_id int [
    ref: > lsp_tas.tas_id,
    note:"Foreing key to lsp_tas table. References in this table were used to compute the linked TAS values."
  ]
  reference_id int [
    ref: > lsp_references.reference_id,
    note:"Foreign key to lsp_references table. Points to all references associated with a given TAS value."
  ]

  Note:"Table that makes it easier to link TAS values to the references that were used to compute the TAS values"

  Indexes {
    tas_id
    reference_id
  }
}

Table lsp_manual_curation {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  reference_id int [
    ref: > lsp_references.reference_id,
    note:"Foreing key to the ls_reference table for this measurement."
  ]
  tas_id int [
    ref: > lsp_tas.tas_id,
    note:"Foreign key to lsp_tas table. Indicates that this value was used to calculate the referenced TAS."
  ]

  Note:'''
    Table of manual compund target binding assertions.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    (lspci_id, lspci_target_id)
    tas_id
  }
}

Enum selectivity_classes {
  most_selective
  semi_selective
  poly_selective
  other_selective
  unknown_selective
}

Table lsp_selectivity {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  selectivity_class selectivity_classes [
    note:"Assertion for the selectivity of the compound to the given target."
  ]
  investigation_bias float
  strength int
  wilcox_pval float
  selectivity float
  tool_score float
  ic50_difference float [note:"Difference between ontarget and offtarget IC50 Q1 measurements"]
  ontarget_ic50_q1 float [note:"First quartile of ontarget IC50 measurements"]
  offtarget_ic50_q1 float [note:"First quartile of offtarget IC50 measurements"]
  ontarget_n int [note:"Number of ontarget IC50 measurements"]
  offtarget_n int [note:"Number of offtarget IC50 measurements"]

  Note:'''
    Table of selectivity assertions of compounds to their targets. See \
    10.1016/j.chembiol.2019.02.018 for details.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    (lspci_id, lspci_target_id)
  }
}

Table lsp_one_dose_scans {
  one_dose_scan_id int [
    pk,
    note:"Primary key for single dose measurements"
  ]
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  source compound_sources [note:"Source of the measurement"]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  percent_control float [note:"Remaining activity of target at the given compound concentration."]
  concentration float [note:"Concentration of the compound in the assay."]
  reference_id varchar [note:"The reference for the measurement."]
  one_dose_scan_agg_id int [
    ref: > lsp_one_dose_scan_agg.one_dose_scan_agg_id,
    note:"Foreign key to lsp_phenotypic_agg table. All measurements with the same ID are aggregated."
  ]

  Note:'''
    Table of single dose compound activity measurements as \
    opposed to full dose-response affinity measurements.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    (lspci_id, lspci_target_id)
    one_dose_scan_id
  }
}

Table lsp_one_dose_scan_agg {
  one_dose_scan_agg_id int [
    pk,
    note:"All measurements with this ID in lsp_one_dose_scans were aggregated."
  ]
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  percent_control float [note:"Aggregated remaining activity of target at the given compound concentration."]
  concentration float [note:"Concentration of the compound in the assay."]
  tas_id int [
    ref: > lsp_tas.tas_id,
    note:"Foreign key to lsp_tas table. Indicates that this value was used to calculate the referenced TAS."
  ]

  Note:'''
    Table of single dose compound activity measurements as \
    opposed to full dose-response affinity measurements.
    All available data for a single concentration and compound target pair were
    aggregated by taking the first quartile.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    tas_id
    (lspci_id, lspci_target_id)
    one_dose_scan_agg_id
  }
}

Table lsp_clinical_info {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  max_phase int
  first_approval int
  oral boolean
  parenteral boolean
  topical boolean
  black_box_warning boolean
  first_in_class boolean
  prodrug boolean
  indication_class varchar
  withdrawn_flag boolean
  withdrawn_year int
  withdrawn_country varchar
  withdrawn_reason varchar

  Note:'''
    Table of the clinical approval status of compounds. \
    Sourced from ChEMBL
  '''

  Indexes {
    lspci_id
    max_phase
  }
}

Enum commercial_tiers {
  "Tier 1" [note:"Ships within one week."]
  "Tier 2" [note:"Ships within two weeks."]
  "Tier 3" [note:"Ships within a month."]
  "Tier NA" [note:"Unkown shipping time"]
}

Table lsp_commercial_availability {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  emolecules_id int [note:"ID of compound at eMolecules"]
  vendor varchar [note:"The name of the vendor"]
  catalog_number varchar [note:"Catalog number of the compound."]
  tier commercial_tiers [note:"Shipment timeframe."]

  Note:'''
    Table of the commercial availability of compounds. \
    Sourced from eMolecules (https://www.emolecules.com/).
  '''

  Indexes {
    lspci_id
  }
}

Enum fingerprint_types {
  morgan_normal
  morgan_chiral
  topological_normal
}

Table lsp_fingerprints {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  fingerprint_type fingerprint_types [
    note:"Three different fingerprint types are available: Morgan fingerprints (either ignoring or respecting stereochemistry) or RDKit topological fingerprints (ignoring stereochemistry)."
  ]
  fingerprint char(512) [note:"256 byte hex-encoded fingerprint"]

  Note:'''
    Table of specificity assertions of compounds to their targets. See \
    10.1016/j.chembiol.2019.02.018 for details.
  '''

  Indexes {
    lspci_id
  }
}

Enum include_reasons {
  selectivity [note:"Compound was included because of it's selectivity for a specific target."]
  clinical [note:"Compound was included because it is an approved drug with an annotated target."]
}

Table lsp_compound_library {
  lspci_id int [
    ref: > lsp_compound_dictionary.lspci_id,
    note:"Foreign key for compound ID"
  ]
  lspci_target_id int [
    ref: > lsp_target_dictionary.lspci_target_id,
    note:"Foreign key for gene ID"
  ]
  gene_id int [note:"Entrez gene ID"]
  symbol varchar [note:"Entrez gene symbol"]
  rank int [note:"Ranking of compounds for the same target. First compound is best."]
  reason_included include_reasons [note:"Compounds can be included either because of their selectivity or because they are approved/in clinical trials."]

  Note:'''
    Library of optimal compounds for each target. See \
    10.1016/j.chembiol.2019.02.018 for details.
  '''

  Indexes {
    lspci_id
    lspci_target_id
    (lspci_id, lspci_target_id)
  }
}
